import { StyleSheet } from 'react-native';
import type { AppTheme } from '../../../../theme';

export const createStyles = (colors: AppTheme['colors']) =>
  StyleSheet.create({
    root: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingVertical: 10,
    },
    back: { paddingVertical: 14 },
    content: { padding: 22, paddingBottom: 40 },
    hero: {
      padding: 24,
      backgroundColor: colors.accentSoft,
      borderRadius: 24,
      marginBottom: 24,
    },
    label: {
      color: colors.accent,
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 2,
    },
    title: {
      color: colors.text,
      fontSize: 42,
      fontWeight: '800',
      marginVertical: 12,
    },
    subtitle: { color: colors.textSecondary, fontSize: 16, lineHeight: 24 },
    testNotificationButton: {
      alignSelf: 'flex-start',
      borderColor: colors.border,
      borderRadius: 12,
      borderWidth: 1,
      marginTop: 16,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    testNotificationText: { color: colors.text, fontSize: 13, fontWeight: '700' },
    progress: { flexDirection: 'row', gap: 6, marginVertical: 20 },
    segment: { flex: 1, height: 5, borderRadius: 3 },
    text: { color: colors.text, fontSize: 15, lineHeight: 23 },
    muted: { color: colors.textSecondary, fontSize: 12, lineHeight: 20 },
    section: {
      color: colors.text,
      fontSize: 17,
      fontWeight: '700',
      marginBottom: 12,
    },
    story: {
      color: colors.text,
      fontSize: 17,
      lineHeight: 29,
      marginVertical: 18,
    },
    action: {
      color: colors.accent,
      backgroundColor: colors.accentSoft,
      padding: 16,
      borderRadius: 16,
      fontSize: 15,
      lineHeight: 23,
    },
    reward: {
      color: colors.accent,
      fontSize: 13,
      lineHeight: 22,
      marginBottom: 20,
    },
    collection: {
      padding: 18,
      borderRadius: 16,
      backgroundColor: colors.surfaceRaised,
      marginBottom: 24,
    },
    choice: {
      padding: 17,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      marginBottom: 10,
    },
    input: {
      color: colors.text,
      backgroundColor: colors.input,
      borderRadius: 16,
      padding: 16,
      minHeight: 80,
      marginVertical: 12,
      textAlignVertical: 'top',
    },
    primary: {
      backgroundColor: colors.accent,
      padding: 17,
      borderRadius: 16,
      alignItems: 'center',
    },
    primaryText: { color: colors.onAccent, fontWeight: '700', fontSize: 15 },
    disabled: { opacity: 0.45 },
    wait: {
      flexDirection: 'row',
      gap: 10,
      justifyContent: 'center',
      padding: 20,
    },
    error: {
      color: colors.error,
      fontSize: 14,
      lineHeight: 22,
      paddingVertical: 12,
    },
    backButton: {
      width: 38,
      height: 38,
      borderRadius: 13,
      backgroundColor: colors.surfaceRaised,
      alignItems: 'center',
      justifyContent: 'center',
    },
    backText: { color: colors.text, fontSize: 31, lineHeight: 33, marginTop: -3 },
  });
