import { StyleSheet } from 'react-native';
import type { AppTheme } from '../../../../theme';

export function createStyles(colors: AppTheme['colors'], isDark: boolean) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
    },
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scrollContent: {
      flexGrow: 1,
      paddingHorizontal: 24,
      paddingTop: 20,
      paddingBottom: 36,
    },
    glow: {
      position: 'absolute',
      width: 260,
      height: 260,
      borderRadius: 130,
      backgroundColor: colors.accent,
      opacity: 0.2,
      top: -60,
      right: -80,
    },
    backButton: {
      width: 38,
      height: 38,
      borderRadius: 13,
      backgroundColor: colors.surfaceRaised,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 16,
    },
    backText: {
      color: colors.text,
      fontSize: 31,
      lineHeight: 33,
      marginTop: -3,
    },
    header: {
      marginBottom: 22,
    },
    badge: {
      width: 108,
      height: 50,
      borderRadius: 17,
      backgroundColor: 'rgba(124, 92, 255, 0.18)',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.14)',
      marginBottom: 18,
    },
    badgeText: {
      color: '#FFFFFF',
      fontSize: 20,
      fontWeight: '700',
    },
    badgeAi: { position: 'relative' },
    badgeSpark: {
      position: 'absolute',
      top: -5,
      left: '50%',
      color: '#17D1FF',
      fontSize: 15,
      transform: [{ translateX: 10 }],
    },
    title: {
      color: colors.text,
      fontSize: 32,
      fontWeight: '800',
      letterSpacing: -0.8,
    },
    subtitle: {
      marginTop: 8,
      color: colors.textSecondary,
      fontSize: 15,
      lineHeight: 22,
    },
    card: {
      backgroundColor: isDark ? 'rgba(15, 23, 42, 0.78)' : colors.surface,
      borderRadius: 26,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 22,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 18 },
      shadowOpacity: 0.22,
      shadowRadius: 26,
      elevation: 10,
    },
    label: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '700',
      marginBottom: 9,
      marginTop: 4,
    },
    inputWrap: {
      minHeight: 54,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.input,
      borderRadius: 15,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 14,
      marginBottom: 14,
    },
    input: {
      flex: 1,
      color: colors.text,
      fontSize: 15,
      paddingVertical: 14,
    },
    error: {
      color: colors.error,
      fontSize: 13,
      lineHeight: 19,
      marginBottom: 12,
    },
    primaryButton: {
      backgroundColor: colors.accent,
      borderRadius: 17,
      paddingVertical: 16,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 4,
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.3,
      shadowRadius: 16,
      elevation: 7,
    },
    disabledButton: {
      opacity: 0.55,
    },
    primaryButtonText: {
      color: '#FFFFFF',
      fontSize: 17,
      fontWeight: '700',
    },
  });
}
