import { StyleSheet } from 'react-native';
import type { AppTheme } from '../../../../theme';

export function createStyles(colors: AppTheme['colors'], isDark: boolean) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
    },
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scrollContent: {
      flexGrow: 1,
      paddingHorizontal: 20,
      paddingTop: 24,
      paddingBottom: 40,
    },
    backgroundGlow: {
      position: 'absolute',
      width: 260,
      height: 260,
      borderRadius: 130,
      backgroundColor: colors.accent,
      opacity: 0.24,
      top: -30,
      right: -60,
    },
    backgroundGlowSecondary: {
      position: 'absolute',
      width: 280,
      height: 280,
      borderRadius: 140,
      backgroundColor: '#17D1FF',
      opacity: 0.18,
      bottom: 140,
      left: -90,
    },
    headerWrap: {
      marginTop: 24,
      marginBottom: 20,
      zIndex: 1,
    },
    badge: {
      width: 112,
      height: 54,
      borderRadius: 18,
      backgroundColor: 'rgba(124, 92, 255, 0.18)',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.14)',
      marginBottom: 20,
    },
    badgeText: {
      color: '#FFFFFF',
      fontSize: 21,
      fontWeight: '700',
    },
    badgeAi: { position: 'relative' },
    badgeSpark: {
      position: 'absolute',
      top: -5,
      left: '50%',
      color: '#17D1FF',
      fontSize: 15,
      transform: [{ translateX: 10 }],
    },
    title: {
      color: colors.text,
      fontSize: 36,
      fontWeight: '800',
      letterSpacing: -1,
    },
    subtitle: {
      marginTop: 10,
      color: colors.textSecondary,
      fontSize: 16,
      lineHeight: 24,
    },
    card: {
      backgroundColor: isDark ? 'rgba(15, 23, 42, 0.72)' : colors.surface,
      borderRadius: 30,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 25,
      zIndex: 1,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 18 },
      shadowOpacity: 0.24,
      shadowRadius: 28,
      elevation: 10,
    },
    label: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '700',
      marginBottom: 10,
      marginTop: 6,
    },
    inputWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.input,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 14,
      marginBottom: 20,
      minHeight: 60,
    },
    inputIcon: {
      fontSize: 18,
      marginRight: 10,
    },
    input: {
      flex: 1,
      color: colors.text,
      fontSize: 16,
      paddingVertical: 16,
    },
    eyeButton: {
      width: 32,
      height: 32,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 16,
      backgroundColor: 'rgba(255,255,255,0.05)',
    },
    eyeText: {
      fontSize: 15,
    },
    row: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 6,
      marginBottom: 22,
    },
    forgotText: {
      color: colors.accent,
      fontSize: 14,
      fontWeight: '600',
    },
    primaryButton: {
      backgroundColor: colors.accent,
      borderRadius: 18,
      paddingVertical: 18,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.35,
      shadowRadius: 18,
      elevation: 8,
    },
    primaryButtonDisabled: {
      opacity: 0.7,
    },
    primaryButtonText: {
      color: '#FFFFFF',
      fontSize: 18,
      fontWeight: '700',
    },
    errorText: {
      color: colors.error,
      fontSize: 13,
      marginBottom: 14,
    },
    dividerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginVertical: 22,
    },
    divider: {
      flex: 1,
      height: 1,
      backgroundColor: 'rgba(148, 163, 184, 0.25)',
    },
    dividerText: {
      marginHorizontal: 14,
      color: colors.textSecondary,
      fontSize: 12,
      textTransform: 'uppercase',
      letterSpacing: 1,
    },
    socialRow: {
      flexDirection: 'row',
      gap: 12,
    },
    socialButton: {
      flex: 1,
      backgroundColor: colors.input,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 13,
    },
    socialIcon: {
      width: 22,
      height: 22,
      marginRight: 8,
    },
    socialText: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '600',
    },
    footer: {
      marginTop: 28,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 1,
    },
    footerText: {
      color: colors.textSecondary,
      fontSize: 15,
    },
    signupText: {
      color: colors.accent,
      fontSize: 15,
      fontWeight: '700',
      marginLeft: 6,
    },
  });
}
