import { StyleSheet } from 'react-native';
import type { AppTheme } from '../../../../theme';

export const deleteActionWidth = 48;
export const rowActionsWidth = deleteActionWidth * 2;

export function createStyles(colors: AppTheme['colors']) {
  return StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: colors.background },
    container: { flex: 1, paddingHorizontal: 16, paddingTop: 14 },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 26,
    },
    eyebrow: {
      color: colors.accent,
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 2,
    },
    title: {
      color: colors.text,
      fontSize: 28,
      fontWeight: '800',
      marginTop: 4,
    },
    profileButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.accentSoft,
      alignItems: 'center',
      justifyContent: 'center',
    },
    profileInitial: { color: colors.accent, fontSize: 17, fontWeight: '700' },
    profileImage: { width: 40, height: 40, borderRadius: 20 },
    greeting: { color: colors.text, fontSize: 19, fontWeight: '700' },
    description: {
      color: colors.textSecondary,
      fontSize: 14,
      lineHeight: 21,
      marginTop: 7,
      marginBottom: 20,
    },
    newChatButton: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 16,
      borderRadius: 20,
      backgroundColor: colors.accent,
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 9 },
      shadowOpacity: 0.25,
      shadowRadius: 16,
      elevation: 6,
    },
    newChatIcon: {
      color: '#FFFFFF',
      fontSize: 28,
      fontWeight: '300',
      marginRight: 13,
    },
    newChatCopy: { flex: 1 },
    newChatTitle: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' },
    newChatSubtitle: { color: '#E0D9FF', fontSize: 12, marginTop: 4 },
    newChatArrow: { color: '#FFFFFF', fontSize: 27, fontWeight: '300' },
    interviewButton: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 14,
      borderRadius: 18,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      marginTop: 10,
    },
    interviewIcon: {
      width: 38,
      height: 38,
      borderRadius: 13,
      backgroundColor: colors.accentSoft,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    interviewIconText: {
      color: colors.accent,
      fontSize: 22,
      fontWeight: '700',
    },
    interviewTitle: { color: colors.text, fontSize: 15, fontWeight: '700' },
    interviewSubtitle: {
      color: colors.textSecondary,
      fontSize: 12,
      marginTop: 3,
    },
    interviewArrow: {
      color: colors.textMuted,
      fontSize: 25,
      fontWeight: '300',
    },
    listHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 28,
      marginBottom: 10,
      gap: 9,
    },
    listTitle: { color: colors.text, fontSize: 16, fontWeight: '700' },
    listCount: {
      color: colors.textSecondary,
      backgroundColor: colors.surfaceRaised,
      overflow: 'hidden',
      borderRadius: 10,
      paddingHorizontal: 8,
      paddingVertical: 2,
      fontSize: 12,
    },
    listContent: { paddingBottom: 10 },
    searchInput: {
      color: colors.text,
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderWidth: 1,
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 11,
      marginBottom: 8,
      fontSize: 14,
    },
    conversationRow: {
      overflow: 'hidden',
      position: 'relative',
    },
    rowActions: {
      alignItems: 'stretch',
      bottom: 0,
      flexDirection: 'row',
      position: 'absolute',
      right: 0,
      top: 0,
      width: rowActionsWidth,
    },
    rowActionButton: {
      alignItems: 'center',
      justifyContent: 'center',
      width: deleteActionWidth,
    },
    renameActionButton: {
      backgroundColor: 'transparent',
    },
    renameIconBackground: {
      alignItems: 'center',
      backgroundColor: colors.accent,
      borderRadius: 19,
      height: 38,
      justifyContent: 'center',
      width: 38,
    },
    renameActionText: {
      color: '#FFFFFF',
      fontSize: 21,
      fontWeight: '700',
    },
    deleteButton: {
      backgroundColor: 'transparent',
    },
    deleteButtonPressed: {
      opacity: 0.8,
    },
    deleteButtonContent: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    deleteIconBackground: {
      alignItems: 'center',
      backgroundColor: '#D94355',
      borderRadius: 19,
      height: 38,
      justifyContent: 'center',
      width: 38,
    },
    trashLid: {
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      borderRadius: 1,
      height: 2,
      marginBottom: 3,
      width: 15,
    },
    trashHandle: {
      backgroundColor: '#FFFFFF',
      borderTopLeftRadius: 1,
      borderTopRightRadius: 1,
      height: 3,
      position: 'absolute',
      top: -3,
      width: 6,
    },
    trashCan: {
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      borderBottomLeftRadius: 3,
      borderBottomRightRadius: 3,
      flexDirection: 'row',
      height: 14,
      justifyContent: 'space-around',
      overflow: 'hidden',
      width: 12,
    },
    trashLine: {
      backgroundColor: '#D94355',
      borderRadius: 1,
      height: 8,
      width: 1.5,
    },
    conversationForeground: {
      backgroundColor: colors.background,
    },
    conversationCard: {
      flexDirection: 'row',
      alignItems: 'center',
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    conversationOpenButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 13,
    },
    conversationIcon: {
      width: 40,
      height: 40,
      borderRadius: 14,
      backgroundColor: colors.accentSoft,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    conversationIconText: { color: colors.accent, fontSize: 21 },
    conversationContent: { flex: 1 },
    conversationTitle: { color: colors.text, fontSize: 14, fontWeight: '600' },
    conversationMeta: { color: colors.textMuted, fontSize: 12, marginTop: 5 },
    chevron: { color: colors.textMuted, fontSize: 24, marginLeft: 10 },
    centered: { padding: 32, alignItems: 'center' },
    emptyState: {
      alignItems: 'center',
      paddingVertical: 35,
      paddingHorizontal: 20,
    },
    emptyIcon: { color: colors.accent, fontSize: 34, marginBottom: 10 },
    emptyTitle: { color: colors.text, fontSize: 15, fontWeight: '700' },
    emptyText: {
      color: colors.textSecondary,
      fontSize: 13,
      textAlign: 'center',
      marginTop: 6,
    },
    error: { color: colors.error, fontSize: 13, marginBottom: 8 },
    modalBackdrop: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 24,
      backgroundColor: 'rgba(0,0,0,0.45)',
    },
    modalKeyboardAvoidingView: { flex: 1 },
    profileMenu: {
      width: '100%',
      maxWidth: 380,
      padding: 20,
      borderRadius: 24,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    profileEditor: {
      width: '100%',
      maxWidth: 380,
      padding: 22,
      borderRadius: 24,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    deleteConfirmation: {
      width: '100%',
      maxWidth: 380,
      padding: 22,
      borderRadius: 24,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    deleteConfirmationTitle: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '700',
    },
    deleteConfirmationMessage: {
      color: colors.textSecondary,
      fontSize: 14,
      lineHeight: 21,
      marginTop: 10,
    },
    renameInput: {
      color: colors.text,
      backgroundColor: colors.input,
      borderColor: colors.border,
      borderWidth: 1,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      marginTop: 16,
      fontSize: 15,
    },
    deleteConfirmationActions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 10,
      marginTop: 22,
    },
    deleteCancelButton: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 16,
      paddingVertical: 11,
      borderRadius: 13,
      backgroundColor: colors.surfaceRaised,
    },
    deleteCancelText: {
      color: colors.textSecondary,
      fontSize: 14,
      fontWeight: '600',
    },
    deleteConfirmButton: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 16,
      paddingVertical: 11,
      borderRadius: 13,
      backgroundColor: '#D94355',
    },
    deleteConfirmText: { color: '#FFFFFF', fontSize: 14, fontWeight: '700' },
    profileMenuHeader: { flexDirection: 'row', alignItems: 'center' },
    profileMenuAvatar: {
      width: 48,
      height: 48,
      borderRadius: 24,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.accentSoft,
      overflow: 'hidden',
    },
    profileMenuAvatarImage: { width: 48, height: 48 },
    profileMenuAvatarText: {
      color: colors.accent,
      fontSize: 18,
      fontWeight: '700',
    },
    profileDetails: { flex: 1, marginLeft: 12 },
    profileName: { color: colors.text, fontSize: 15, fontWeight: '700' },
    profileEmail: { color: colors.textMuted, fontSize: 12, marginTop: 3 },
    closeButton: {
      width: 32,
      height: 32,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 16,
      backgroundColor: colors.surfaceRaised,
    },
    closeButtonText: {
      color: colors.textSecondary,
      fontSize: 24,
      lineHeight: 27,
    },
    menuDivider: {
      height: 1,
      backgroundColor: colors.border,
      marginVertical: 18,
    },
    menuSectionTitle: {
      color: colors.textSecondary,
      fontSize: 13,
      fontWeight: '700',
      marginBottom: 10,
    },
    preferencesRow: {
      backgroundColor: colors.surfaceRaised,
      borderColor: colors.border,
      borderRadius: 18,
      borderWidth: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
      padding: 12,
      width: '100%',
    },
    preference: {
      alignItems: 'flex-start',
    },
    menuEditProfileButton: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    menuEditProfileIcon: {
      width: 38,
      height: 38,
      borderRadius: 13,
      backgroundColor: colors.accentSoft,
      alignItems: 'center',
      justifyContent: 'center',
    },
    menuEditProfileIconText: {
      color: colors.accent,
      fontSize: 20,
      fontWeight: '700',
    },
    menuEditProfileCopy: { flex: 1, marginLeft: 12 },
    menuEditProfileTitle: { color: colors.text, fontSize: 14, fontWeight: '700' },
    menuEditProfileSubtitle: { color: colors.textMuted, fontSize: 12, marginTop: 3 },
    menuEditProfileArrow: { color: colors.textMuted, fontSize: 24 },
    menuLogoutButton: {
      alignItems: 'center',
      marginTop: 20,
      paddingVertical: 13,
      borderRadius: 14,
      backgroundColor: colors.accentSoft,
    },
    menuLogoutText: { color: colors.accent, fontSize: 14, fontWeight: '700' },
    profileEditorDescription: {
      color: colors.textSecondary,
      fontSize: 13,
      marginTop: 6,
    },
    profileEditorLabel: {
      color: colors.textSecondary,
      fontSize: 13,
      fontWeight: '700',
      marginTop: 18,
      marginBottom: -8,
    },
    profileEditorDivider: {
      height: 1,
      backgroundColor: colors.border,
      marginVertical: 20,
    },
    profileEditorPasswordTitle: { color: colors.text, fontSize: 15, fontWeight: '700' },
    profileEditorHint: {
      color: colors.textMuted,
      fontSize: 12,
      lineHeight: 18,
      marginTop: 4,
      marginBottom: 10,
    },
    profileEditorInput: {
      color: colors.text,
      backgroundColor: colors.input,
      borderColor: colors.border,
      borderWidth: 1,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      marginTop: 9,
      fontSize: 15,
    },
    profileSaveButton: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 16,
      paddingVertical: 11,
      borderRadius: 13,
      backgroundColor: colors.accent,
    },
  });
}
